        // Daftar barang
        const barang = [
            "Ada beberapa teknik internalisasi nilai bagi seseorang. ('Norma etika maupun norma hukum') ",
            "Ada beberapa teknik internalisasi nilai bagi seseorang. ('Change belief')",
            "Ada berbagai teknik internalisasi nikai nilai ke dalam diri setiap ASN ('Multi protection of integrity')",
            "Adaptasi Dalam Business Process Pemerintahan ('Mempertahankan dan meningkatkan kinerja')",
            "Aktualisasi nilai nilai dasar komitmen mutu ('Iklim atau budaya kerja uggul yang dapat menumbuhkan keberanian untuk menampilkan kreativitas dan inovasi')",
            "Akuntabilitas merupakan kontrak antara pemerintah ('Akuntabilitas adalah interaksi, pertukaran social dua arah antara yang menuntut')",
            "Alat akuntabilitas birokrasi di indonesia antara lain sebagai ('Alokasi anggaran')",
            "Alat pemastian mutu pelanggan terdiri dari ('Fisiologi')",
            "Anggapan yang dimiliki terhadap suatu kelompok yang bersifat tidak baik ('Strereotip suatu kelompok')",
            "Apabila dalam prosedur yang digunakan dalam ('Akuntabilitas Proses')",
            "Apakah istilah lain dari parkinsonian birokrasi ('Pelayanan regulative')",
            "Apakah yang dimaksud dengan prinsip tender loving care ('wujudan atau pelaksanaan sistem merit pada instansi pemerintah')",
            "Apakah yang dimaksud dengan siklus pelayanan ('Sebuah rangkaian peristiwa yang dilalui pelanggan sewaktu menikmati atau menerima layanan yang diberikan')",
            "ASN pembelajar yang relevan saat ini adalah ('Pegawai yang memiliki kemampuan menerapkan kompetensinya kesituasi baru, ')",
            "ASN sebagai profesi, salah satunya berlandaskan pada prinsip Nilai Dasar ('Undang-Undang Nomor 5 Tahun 2014')",
            "Azas etika politik masyarakat agar setiap bentuk kekuasaan ('Melakukan monitoring dan evaluasi pelaksanaan kebijakan dan manajemen ASN untuk menjamin')",
            "Azas etika public mensyaratkan agar setiap bentuk kekuasaan pejabat dibatasi dengan ('Norma etika maupun norma hokum')",
            "Badan dan/atau pejabat pemerintahan dapat menolak memberikan bantuan kedinasan ('bantuan Belum mendapatkan persetujuan dari DPR')",
            "Badan Dan/Atau Pejabat Pemerintahan Dapat Menolak Memberikan ('Mempengaruhi kinerja Bandan dan/atau pejabat')",
            "Bagi Seorang Pegawai Negeri Sipil, Kata Loyal ('NKRI')",
            "Beberapa istilah baru terkait perkembangan ICT terkait model ('Use generated content')",
            "Beberapa kata kunci yang perlu diketahui dan dilaksanakan ('Atensi, senyum, salam, tolong, maaf dan terima kasih')",
            "Beberapa perilaku pelayanan prima yang perlu ('Cepat dan terlihat sibuk')",
            "Berdasarkan ,model incremental pada Negara ('Hasil penilaian dan analisis empiris terhadap jadwal dan kebijakn publicyang telah dilaksanakan')",
            "berdasarkan undang-undang ASN, kode etik ('Motivasi dan kemampuan')",
            "Berikut adalah bentuk partisipasi masyarakat dalam penyelenggaraan ('Penganggaran')",
            "Berikut adalah cara cara untuk berinovasi ,kecuali ('Dengan cara duplikasi')",
            "Berikut adalah ciri masalah yang berada pada sector public kecuali ('Masalah yang mempunyai akibat lebih luas termasuk akibat yang mengenai orang yang tidak langsung terlibat')",
            "Berikut adalah ciri-ciri penting yang membedakan antara sektor publik dan sektor swasta, kecuali. ('korporasi') ",
            "Berikut adalah definisi pelayanan public,kecuali ('Kegiatan ataurangkaian kegiatan dalam rangka pemenuhan kebutuhan pelayanan sesuai dengan peraturan perundang undangan bagi setiap warga Negara.')",
            "Berikut adalah factor factor yang mempengarui kualitas pelayanan public ,kecuali ('Masyarakat')",
            "Berikut adalah makna dari service menurut Christoper H Lovelock  Kecuali ('Ada bentuk yag dapat dimiliki')",
            "Berikut Adalah Situasi Yang Mencerminkan Terlaksananya Whole-Of-Government (Wog) Kecuali ('Silo Mentality Aparatur Sipil Negara') ",
            "Berikut adalah termasuk Alat Akuntabilitas ('Semua jawaban benar')",
            "Berikut Adalah Unsur Dari Gratifikasi ('Semua jawaban Benar')",
            "Berikut ini adalah beberapa indikator yang menunjukkan ('Status quo')",
            "Berikut ini adalah bentuk kode etik ASN yang tertuang dalam UU ASN kecuali ('Menggunakan kekayaan dan barang milik Negara untuk keperluan pribadi')",
            "Berikut ini adalah bentuk perilaku dalam kode etik menurut UU ASN yang paling tepat ('Menggunakan kekayaan dan barang milik negara secara bertanggung jawab,')",
            "Berikut Ini Adalah Ciri Ciri Penerapan Budaya Adaptif, Kecuali ('Konsisten dengan keputusan yang sudah diambil sejak awal')",
            "Berikut ini adalah indikator suasana lingkungan bekerja yang harmonis ('Seluruh ASN suka saling membantu')",
            "Berikut ini adalah konsep yang mengandung prinsip-prinsip governance kecual ('Collaboration')",
            "Berikut ini adalah lima disiplin yang dikembangkan Peter Senge dalam learning organization, kecuali ('Flexible system')",
            "Berikut Ini Adalah Manfaat Kolaborasi Dalam Penyelenggaraan Pemerintah, Kecuali (' menghilangkan silo mentality')",
            "Berikut ini adalah manfaat kolaborasi dalam penyelenggaraan pemerintahan, kecuali ('Meningkatkan kompetisi antar daerah')",
            "Berikut ini adalah proses kolaboratif, kecuali ('Win win solution')",
            "Berikut Ini Adalah Proses Kolaboratif, Kecuali ('Win win solution')",
            "Berikut ini adalah termasuk akuntabilitas yang sesuai dengan konteks core ('Kemampuan menggunakan kekayaan dan barang milik negara secara bertanggungjawab')",
            "Berikut ini adalah termasuk Prinsip Keterbukaan Informasi, kecuali ('Permintaan informasi harus disertai dengan alasan')",
            "Berikut ini adalah unsur dari Gratifikasi ('Semua jawaban benar')",
            "Berikut ini beberapa indikator yang menunjukkan sebuah organisasi yang berkarakter adaptif, kecuali ('Status quo')",
            "Berikut ini contoh cara mengindentifikasi konflik kepentingan ,kecuali ('Mengindentifikasi bagaiman agar dapat memberikan keuntungan finansial bagi pribadi')",
            "Berikut ini pengertian proses perumusan proposan kebijakan ('Menyusun dan membuatkan serangkaian jadwal pemerintah')",
            "Berikut ini termasuk Kode Etik dari nilai dasar berakhlak, kecuali ('Loyal kepada atasan')",
            "Berikut ini yang bukan kelompok jabatan dalam PNS adalah ('Jabatan structural')",
            "Berikut ini yang bukan prinsip pelayanan publik yang baik untuk mewujudkan pelayanan prima adalah ('Red Tape')",
            "Berikut merupakan contoh pelanggaran integritas dan etika public dalam lingkungan kerja ('Semua jawaban benar')",
            "Berikut pernyataan yang paling sesuai antara lain tentang ASN ('ASN sebagai profesi memiliki kewajiban mengelola dan mengembangkan dirinya')",
            "Berikut pernyataan yang paling sesuai terkait konsepsi kompetensi ('Aspek pengetahuan, keterampilan, dan sikap yang diperlukan')",
            "Berikut Pernyataan Yang Paling Sesuai Terkait Konsepsi ('Aspek pengetahuan, ketrampilan, dan sikap yang diperlukan')",
            "Berikut unsur penting dalam pelayanan public,kecuali ('Bentuk layanan')",
            "Berikut urutan tingkatan akuntabilitas ('Personal, individu, kelompok, organisasi, stakeholder')",
            "Berikut Urutan Tingkatan Akuntabilitas Adalah: ('Personal, individu, kelompok, organisasi, stakeholder')",
            "Berikut yang bukan merupakan bentuk- bentuk patologi birokrasi adalah ('Tidak adanya praktik KKN dan tidak adanya konflik kewenangan')",
            "Berpikir terbuka, dengan belajar hal yang berbeda ('Learn, Unlearn, dan Relearn')",
            "Budaya yang berorientasi pelayanan dapat dijabarkan dengan kriteria sebagai berikut, kecuali ('ASN harus memahami sumber daya yang tersedia')",
            "Complier adalah ('Subyek penegakan,yaitu mereka harus mematuhi hokum dan peraturan isalnya wajib pajak')",
            "Contoh dari keterbukaan dalam kehidupan berbangsa ('Rasa toleransi')",
            "Contoh laporan sebagai bentuk akuntabilitas kinerja dalam lingkup borokrasi yaitu ('Laporan kinerja instansi pemerintah')",
            "Contoh perilaku PNS yang diharapkan ('PNS menyebarkan informasi pemerintah yang belum dipastikan kebenaranya melalui media social')",
            "Contoh prinsip yang memenuhi integritas publik adalah ('meningkatkan produktivitas organisasi')",
            "Daerah dapat melakukan penyederhanaa jenis ('Peraturan daerah ( perda )')",
            "Dakam menciptakan lingkungan kerja yang akuntabel ('AAA Kepentingan')",
            "Dalam kompetensi Aman Bermedia Digital, ada lima kompetensi yang harus dipahami dan diterapkan kecuali ('Mewaspadai hate speech')",
            "Dalam konteks Indonesia ,menurut azyumardi azra ('Kepantasan social')",
            "Dalam Memahami Dan Memenuhi Kebutuhan Masyarakat, Kedudukan Masyarakat Dalam Konteks Tersebut ('Masyarakat sebagai penerima layanan')",
            "Dalam menjalankan amanah terkait dengan tugas pelayanan public ('Pelayanan prima')",
            "Dalam menjalankan tugas dan fungsinya untuk menyelenggarakan ('pemerasan')",
            "Dalam penyelenggaraan pelayanan publik pemerintah wajib ('responsif')",
            "Dalam penyelenggaraan pelayanan publik yang dibutuhkan masyarakat ('Partisipatif')",
            "Dalam penyelenggaraan pelayanan publik, pemerintah sebagai penyelenggara ('Transparan')",
            "Dalam Peraturan Menteri PANRB Nomer 30 Th 2014, inovasi pelayan publik dimaknai ('Terobosan jenis pelayanan baik yang merupakan gagasan atau ide kreatif orisinal dan atau adaptasi atau modifikasi yang memberikan manfaat bagi masyarakat,')",
            "Dalam PP No,53 tahun 20120 tentang disiplin ('Hukuman disiplin berat bisa diberlakukan jika sasaran kerja pegawai kirang dari 25%')",
            "Dalam rangka mencapai tujuan nasional, diperlukan Aparatur Sipil Negara yang mampu ('Mengimplementasikan nilai-nilai berAKHLAK')",
            "Dalam suatu kasus yang tidak dapat diselesaikan dengan cara biasa, ASN dituntut untuk ('Melalukan inovasi dan menggerakan sumber daya yang ada untuk menyelesaikan permasalahan tersebut')",
            "Dalam sumpah/ janjinya PNS berkomitmen untuk ('Menjunjung tinggi kehormatan negara, pemerintah & martabat pegawai negeri sipil')",
            "dalam UU 31 tahun 1999, jo UU No 21 Tahun 2001, Jelaskan bentuk-bentuk/Jenis korupsi ('Melaksanakan tugasnya sesuai dengan perintah atasan atau pejabat yang berwenang meskipun bertentangan dengan ketentuan peraturan')",
            "Dalam UU No 31 tahun 1999, UU No21 itu tahun 2001, dijelaskan bentuk-bentuk jenis korupsi.('Simbolisasi') ",
            "Dalam uu no.31 tahun 1999 jo UU No 21 tahun 2001 dijlaskan bentuk bentuk 0 jenis korupsi, ('Penyuapan')",
            "DAMPAK KORUPSI dalam kehidupan merusak dalam jangka waktu yang lama, ('Diri pribadi,keluarga besar,masyarakat dan proses kehidupan yangblebih luas')",
            "DAMPAK KORUPSI dalam kehidupan merusak dalam jangka waktu yang lama, ('Menurunkan kredibilitas organisasi')",
            "Dari pernyataan dibawah ini ,manakah yang lebih tepat dan perlu menjadi pola piker PNS yang anti korupsi ('Memastikan adanya kesadaran anti korupsi terlebih dahulu hingga muncul niat memberantas atau anti korupsi,')",
            "dari segi moralitas, kekuasaan harus memiliki legitimasi Yang kuat. pernyataan ini mengandung makna ('Analisis jabatan dan analisis beban kerja')",
            "Dari segi moralitas,kekuasaan harus memiliki legitimasi yang kuat('Kewenangan atau keabsahan dalam memegang kekuasaan')",
            "Definisi Whole Of Government (Wog) Adalah: ('Pendekatan penyelenggaraan pemerintahan yang menyatukan upaya upaya kolaboratif pemerintahan dari seluruh sector dalam ruang lingkup koordinasi')",
            "Dengan Berlakunya Tatanan Nilai Berakhlak , Untuk Perilaku Kompeten? ('Jawaban : A dan C Benar')",
            "Dengan berlakunya Undang-undang Nomor 5 Tahun 2014 tentang ASN ('Sekurang-kurangnya 20 (dua puluh) jam Pelajaran bagi PNS danmaksimal 24 (dua puluh empat)')",
            "Di Australia, WoG dimotori oleh Australia public service (APS) dalam laporannya berjudul ('Connecting government ')",
            "di Australia, WOG dimotori oleh Australia ('Standar pelayanan pelanggan, ganti rugi pelanggan, jaminan mutu, audit mutu, penanganan keluhan pelanggan dan Ombudsman')",
            "Dibawah ini merupakan fungsi dari mutu, kecuali ('Memperlakukan orang lain/pelanggan sebagaimana ingin diperlakukan')",
            "Dimensi etika publik yang paling tepat meliputi ('Pelayanan publik')",
            "Disebut dengan apakah kebijakan yang dibuat oleh pemerintah ('Protective regulatory policy')",
            "disebut dengan Apakah problem yang menjerat birokrasi ('Peraturan Menteri')",
            "Diskresi administrasi menjadi starting pont bagi ('Kebebasan Pejabat dalam mengambil keputusan berdasarkan pertimbangan sendiri')",
            "ecara sederhana, definisi pelayanan publik berdasarkan Agus Dwiyanto adalah ('Semua jenis pelayanan untuk menyediakan barang/jasa yang dibutuhkan oleh masyarakat yang memenuhi kriteria')",
            "secara sederhana, definisi pelayanan publik berdasarkan Agus Dwiyanto adalah ('Semua jenis pelayanan untuk menyediakan barang/jasa yang dibutuhkan oleh masyarakat yang memenuhi kriteria')",
            "Etika merupakan cabang fisafat moral yang mencoba ('Gene Biccker')",
            "Fondasi organisasi adaptif terdiri atas, kecuali ('Prosedur')",
            "Hal utama yang menjadi pertimbangan dalam manajemen ('Kualifikasi,kompetensi dan kinerja ASN')",
            "Hal yang diharapkan dari akuntabilitas adalah ('Opurtunis')",
            "Hal yang harus ditanamkan dalam mengantisipasi potensi ('Sikap mendahulukan kepentingan diri sendiri')",
            "Hal yang mencerminkan nilai keunggulan produk / jasa ('mutu')",
            "Hubungan antara pemerintah pusat dan pemerintah daerah serta ('Asas desentralisasi')",
            "Ide WOG dalam mengintegrasikan sektor-sektor ke ('Toni Blair ')",
            "Inovasi muncul karena adanya dorongan ('Kebutuhn organisasi untuk beradaptasi dengan tuntutan perubahan lingkungan')",
            "Istilah asuransi budaya yang memberikan banyak interpretasi ('Weick')",
            "Jika dalam pelaksanaan tugas tidak memperhatikan efektivitas ('Tersedianya Pagu anggaran')",
            "k pegawai secara nasional disebut dengan ('penggelapan dalam jabatan')",
            "Karakteristik Adaptif Dibutuhkan Makhluk Hidup Untuk, Kecuali ('mengatasi ancaman')",
            "Karakteristik dalam memberikan pelayanan prima ('Standardisasi dan sertifikasi kompetensi pemberi layanan')",
            "Kategori tingkat adaptasi negara-negara dalam mendukung WOG ('Persaingan yang tinggi di tingkat Internasional')",
            "Kategori tingkat adaptasi negara-negara dalam mendukung WoG ('Portal masing-masing kementerian dan lembaga')",
            "Kebijakan adaptif dikonseptualisasi oleh elemen kapabilitas ('Thinking ahead ')",
            "Kegagapan dalama mengoperasikan teknologi digital ('Digital immigrant ')",
            "Kegiatan dalam rangka pemenuhan kebutuhan pelayanan sesuai peraturan ('Sinkronisasi dan harmonisasi dengan daerah')",
            "Keselarasan antara apa yang diucapkan dan apa yang dilakukan ('Integritas')",
            "Ketaatan memeneuhi ketentuan waktu kerja ('Wujud perilaku beretika')",
            "Ketika birokrasi sebagai penyelenggara pelayanan public ('Korporasi')",
            "Ketika birokrasi sebagai penyelenggara pelayanan public ('Patologi birokrasi')",
            "Ketika seorang pegawai memiliki sikap loyal dan loyalitas ('Berani untuk mengembangkan berbagai inovasi demi kepentingan organisasi')",
            "Keuntungan diterapkannya system merit bagi organisasi ('Mengakomodasi pertimbangan subjektif dalam penilaian seorang ASN')",
            "Kolaborasi, kebersamaan, kesatuan, tujuan bersama ('Prinsip-prinsip WoG')",
            "Kompetensi terkait nilai dan tata urutan berperilaku ('Digital ethice ')",
            "Konsep Kesenjangan Digital Pada Awalnya Meliputi Hal ('Kemampuan berbagi pesan digital')",
            "kualiTAS pelayanan public dapat dilihat dari ('Tersedianya pagu anggaran.')",
            "kualitas pelayanan publik dapat dilihat dari ('Evolusioner')",
            "Landasan piker yang memungkinkan terjadinya ('Keberanian berimajinasi berinisiatif untuk menampilkan kreativitas dan kemampuan berpikir kritis')",
            "Loyalitas merupakan kualitas kesetiaan atau ('Sikap dan tindakan')",
            "Loyalitas tertinggi setiap orang yang diberikan kepada ('Nasionalisme')",
            "Manfaat keanekaragaman bangsa Indonesia yang paling tepat adalah ('Membuat Indonesia terkenal dimata dunia berkat keragaman budaya yang kita miliki')",
            "Melakukan hal yang inovatif, dengan mengetahu ('Opurtunis')",
            "Membangun system integritas memerlukan upaya ('Mengupayakan agar pemimpin berlaku adil terhadap karyawan')",
            "Memberi atau menjanjikan sesuatu kepada pegawai ('Suap menyuap')",
            "Memberikan layanan melebihi harapan customer ('Meningkatkan mutu layanan dan tidak boleh berhenti ketika kebutuhan customer sudah dapat terpenuhi')",
            "Menghadapi volatility adalah dengan cara menegaskan ('visi')",
            "Menurut A. Imanto, Siklus Layanan Dimulai Pada ('Dimulai pada saat konsumen mengadakan kontak pertama kali dengan service selivery system dan berakhir sampai dengan selesai jasa')",
            "Menurut Catalano,etika sebenarnya dapat dipahami sebagai 1 ('1,2 dan 3 yang benar')",
            "Menurut Robert kligaard formula for corruption adalah ('Corruption /jorupsi(C ).Monopoli ( M),Dikoresi / Diskresi / kekuasaa dan akuntabilitas')",
            "Model interaksi yang terjadi dalam governance adalah sebagai berikut, kecuali ('Non voluntary')",
            "Nama Pahlawan Nasional oto iskandar dinata disebut sebagai ('Si jalak harupat')",
            "Nasionalisme dalam konteks loyalitas seorang ASN dapat dimaknai sebagai ('Suatu keadaan atau pikiran yang mengembangkan keyakinan bahwa kesetiaan terbesar')",
            "nasionalisme dapat dipandang sebagai suatu paham kebangsaan yang diwujudkan ('kesetiaan rakyat kepada negara')",
            "Negara berkewajiban melayani setiap warga negara dan penduduk untuk ('Pembukaan Alinea ke IV')",
            "Negara bukan menjadi satu-satunya penyelenggara pemerintah ('Governance')",
            "Pegawai ASN dapat diandalkan dalam memberikan pelayanan ('Mampu akan dan pasti menyelesaikan tugas yang mereka terima')",
            "Pegawai negri atau penyelenggara Negara baik langsung maupun ('Penggelapan dalam jabatan')",
            "Pegawai yang diangkat sebagai pegawai tetap oleh pejabat ('Sektor publik memanfaatkan lebih banyak orang yang memiliki motivasi yang sangat beragam')",
            "Pejabat public yang paling kapabel dan berntuk memberikan akses ('Semua unsur aparatur dalam birokrasi')",
            "Pelayanan melalui kebijakan public yangbmengatur sendi ('Pelayanan regulative')",
            "Pelayanan melalui kebijakan publik yang mengatur sendi ('Sebagai alat untuk beradaptasi dengan perubahan')",
            "Pelayanan publik harus dapat dipertanggungjawabkan ('Akuntabel')",
            "Pelayanan publik yang diselenggarakan oleh pemerintah tidak boleh dibedakan ('Tidak diskriminatif')",
            "Pelayanan yang diberikan oleh pemerintah kepada masyarakat ('prima')",
            "Pelopor pergerakan kaum wanita pertama di Indonesia adalah ('R.A.Kartini')",
            "Pemberian hadiah kepada penyelenggara negara, dengan maksud ('Materialitas')",
            "pemerintah ditingkat pusat maupun sektor banyak menerbitkan ('Mengutamakan keseimbangan antara hak dan kewajiban pegawai ASN')",
            "Pemerintah sudah memulai program pengadaan barang ('Akuntabilitas kejujuran dan hokum')",
            "Pemimpin Sebenarnya Dalam Organisasi Adaptif Adalah ('Perubahan Adaptif')",
            "Pendekataan analisis yang digunakan dalam model pilihan public ('Fiisologi')",
            "Pendekatan analisis yang di gunakan dalam model pilihan publik ('Membuat terlalu percaya diri')",
            "Pendekatan Whole of government di beberapa negara dipandang ('New public management')",
            "Pendekatan wog dapat dilihat dan dibedakan berdasarkan perbedaan kategori ('Koordinasi, integrasi, kedekatan dan pelibatan')",
            "Pendekatan WOG dengan mendorong terjainya merger atau akuisisi kelembagaan ('Kepastian SDM dan Institusi')",
            "Pendekatan WoG ini sudah dikenal dan lama berkembang terutama di negara-negara ('Anglo saxon')",
            "Pendekatan WOG ini sudah dikenal dengan lama berkembang terutama ('Kewenangan atau keabsahan dalam memegang kekuasaan')",
            "Pendekatan Yang Melibatkan Sejumlah Kelembagaan Yang ('Collaboration')",
            "penderitaan yang dialami rakyat akibat penjajahan Belanda ('memengaruhi timbulnya pergerakan nasional')",
            "Pengamalan sila ke 5 dalam lingkup literasi digital dalam lanskap ('Menerapkan netiket dan berprilaku baik sebagai warga digital')",
            "Pengamalan sila pertama Pancasila dalam lingkup literasi digital ('Memiliki paham multi- perspektif terkait keyakinan users')",
            "Pengelolaan ASN untuk menghasilkan pegawai ASN yang professional ('Manajemen ASN')",
            "Pengembangan kompetensi PNS dapat dilakukan di dalam ('Magang')",
            "Pengertian kode etik atadalah ('Aturan aturan yang mengatur tingkah laku dalam suatu kelompok')",
            "Pengertian masyarakat dalam Undang-Undang Nomor 25/2009 tentang Pelayanan Publik ('Seluruh pihak, baik warga negara maupun penduduk sebagai orangperseorangan, kelompok, maupun badan hukum')",
            "Sesuai kebijakan hak pengembangan ASN dalam Undang-undang ASN ('Penyelenggara pelayanan publik harus menyediakan akses bagi warga negara untuk mengetahui ('Transparan ')",
            "Penyelenggaraan kebijakan dan manajemen ASN berdasarkan pada asas kepastian hokum ('Setiap penyelenggaraan kebijakan dan manajemen ASN,Mengutamakan landasan peraturan')",
            "Penyelenggaraan kebijakan dan manajemen ASN berdasarkan pada asas proporsionalitas ('Diri pribadi, keluarga besar, masyarakat dan proses kehidupan yang lebih luas.')",
            "Penyelenggaraan kebijakan dan manajemen ASN berdasarkan pada asas proporsionalitas ('Mengutamakan keseimbangan antar hak dan kewajiban pegawai ASN')",
            "Penyelenggaraan pelayanan publik dilakukan dengan menggunakan fasilitas dan sumber daya manusia ('Akuntabel')",
            "Penyelenggaraan pelayanan publik yang dilakukan oleh pemerintah memiliki ('Berkeadilan ')",
            "Pergerakan nasional yang memperjuangkan cita cita ('Melakukan kerjaama dengan pemerintah belanda')",
            "Perilaku tertutup, politis dan birokratis menunjukkan organisasi berkarakteristik ('Tidak adaptif')",
            "0 Perilaku yang dapat menjadi teladan penegakan etika dan integritas public yang paling tepat ('PENEGAKAN HUKUM SEUAI KETENTUAN YANG BERLAKU')",
            "Perilaku yang tidak dapat menjadi teladan dalam menegakkan etika ('Menjadi penggun nahkoda dan suka berjudi')",
            "Pernyataan berikut sesuai dengan prinsip governance, kecuali ('Pemerintah menjadi satu-satunya actor pelayanan publik')",
            "Pernyataan di bawah ini menggambarkan perilaku kompeten ASN ('Meningkatkan kompetensi diri untuk menjawab tantangan yang selalu berubah adalah keniscayaan bagi setiap ASN')",
            "Pilihan pernyatan yang paling tepat : ('Akuntabilitas, personal mengacu pada nilai-nilai yang ada pada diri seseorang seperti, kejujuran,integritas, moral, dan etika')",
            "Pilihlah pernyataan yang paling tepat ? ('Integritas adalah nilai yang dapat mengikat setiap unsur pelayanan publik secara moral dalam membentengi institusi')",
            "Pilihlah Pertanyaan Yang Paling Tepat ('akuntabilitas dan integritas masyarakat juga menjadi usnsur penting terbentuknya pelayanan public yang baik')",
            "Pimpinan sebenarnya dalam organisasi adaptif adalah pimpinan yang mampu ('Peubahan adaptif')",
            "PNS dapat berpindah antar dan antara kelompok jabatan berdasarkan kepada ('Kualifikasi kompetensi dan penilaian kinerja')",
            "PNS menjadi figur dan teladan di lingkungan masyarakatnya, caranya ('Menjadi bagian dari problem solver (pemberi solusi)')",
            "PNS perlu meningkatkan citranya menjadi pelayan masyarakat dengan menganalkan ('Intoleransi keberagaman')",
            "Praktik WOG dalam jenis pelayanan administrasi dapat dilihat ('PTSP')",
            "Prinsip nasionalisme bangsa Indonesia dilandasi nilai-nilai Pancasila ('Sila ketiga')",
            "Prinsip pelayanan publik yang baik adalah ('Responsif, efektif dan efisien, akuntabel, transparan')",
            "Produksi Konten Yang Berlandaskan Pancasila Dan Bhinneka Tunggal Ika ('Cinta kasih, keselarasan, harmoni dalam keberagaman, demokrasi dan kekeluargaan')",
            "Produktivitas kerja yang berbasis kreativitas diarahkan ('Efisiensi dan efektivitas')",
            "Program DPRD kabupaten wonogiri,provinsi jawa tengah mengevaluasi ('Relevansi')",
            "PROSES INOVASI yang terjadi secara perlahan disebut ('Evolusoiner')",
            "Proses inovasi yang terjadi secara perlahan disebut ('Connecting government')",
            "Responsibilitas terbagi dua aspek, yaitu ('Responsibilitas perseorangan dan institusi')",
            "Ruang lingkup pelayanan publik meliputi pendidikan, ('Pasal 5 ayat 2 UU No.25 Tahun 2009')",
            "Salah satu factor yang dapat menyatukan dan mengikat organisas ('Adanya tujuan yang sama,yaitu ingin mencapai kemerdekaan')",
            "Salah satu factor yang menjadikan beberapa masyarakat Indonesia tidak mau ('Adanya tidakpatuhan selektif terhadap hokum')",
            "Salah satu faktor dalam negeri yang mempercepat munculnya nasionalisme ('penderitaan akibat penjajah')",
            " Salah satu fungsi kelompok kepentingan dalam proses kebijakan ('Penghubung antar rakyat dengan perumus kebijakan')",
            "Salah satu lembaga yang berwenang untuk menjamin keberlangsungan ('The right man on the right job')",
            "SALAH SATU LEMBAGA YANG BERWENANG UNTUK MENJAMIN ('Melakukan monitoring dan evaluasi pelaksanaan kebijakan dan manajemen ASN UNTUK MENJAMIN PERWUJUDAN')",
            "Salah satu pendorong pentingnya ASN selalu meningkatkan kompetensi ('Perubahan dinamika dunia VUCA')",
            "Salah Satu Penguatan Infrastruktur Backbone Untuk Percepatan Digital ('Perluasan kabel serat optik didarat dan laut')",
            "Salah satu peran Indonesia dalam penerapan politik bebas aktif ('Menjadi mediator dalam konflik kamboja dengan melaksanakan Jakarta informal meeting (JIM)')",
            "Salah satu persoalan yang sering dijumpai dalam pelayanan publik ('diskriminatif')",
            "Salah satu prinsip pelayanan publik adalah ('Transparan')",
            "Salah satu prinsip pelayanan publik yang baik untuk mewujudkan ('Pelayanan publik yang diselenggarakan oleh pemerintah harus dapat dijangkau oleh warga negara yang membutuhkan')",
            "Salah satu produk WOG yang dilakukan dala WGA atau Whole of government Accounts ('inggris')",
            "Satu hal yang mendasar yang membedakan inovasi di sektor public ('Transferabilitas inovasi')",
            "Satu Hal Yg Mendasar Yg Membedakan Inovasi Di Sector Public ('penggunaan anggaran yang tidak profit-oriented')",
            "Sebagai ASN membiasakan belajarlah hal-hal yang benar-benar baru ('Learn ')",
            "Sebuah informasi yang tidak benar namun orang yang menyebarnya ('Misinformasi')",
            "Sebuah perangkat lunak yang dirancang untuk mengontrol perangkat ('Spyware')",
            "Sebuah rangkaian peristiwa yang dilalui pelanggan sewaktu ('Siklus pelayanan')",
            "Sebutkan yang bukan merupakan fungsi ASN? ('Pengawas kegiatan publik')",
            "Secar umum,subtansi laporan kinerja pada instansi pemerintahberisi sebagai berikut,kecuali ('Akuntabilitas keuangan')",
            "Secara etimologi istilah loyal diadaptasi dari bahasa prancis yaitu ('Mutu dari sikap setia') ",
            "Segala bentuk kegiatan pelayanan umum yang dilaksanakan oleh Instansi ('Pelayanan Publik ')",
            "Sejarah awal kebangkitan nasionalisme di Indonesia ditandai dengan ('Budi utomo')",
            "Sejarah keseluruhan dalam rumusan pancasila begitu a lot dalam pembahasannya ('Panitia yang terdiri atas 3 golongan kebangsaan dan 6 golongan islam')",
            "Selain dilakukan berdasarkan kualifikasi,kompetensi,penilaian kinerja ('Integrasi dan moralitas')",
            "Selama ini instansi pemerintah mengusulkan formasi perekrutan PNS ('Kita kekurangan hakim yang baik dan kelebihan hakim yang tidak baik')",
            "Seorang ASN diharapkan dapat diandalkan untuk memberikan pelayanan prima ('Melakukan pelayanan maksimal sesuai dengan tugas fungsinya')",
            "Seorang ASN harus mengetahui dan menguasai etiket bertamu dan menerim tamu ('Berpenampilan berlebihan')",
            "Sesuai permenpan dan RB 38 tahun 2017 tentang standar jabatan ASN ('Teknis, manajerial dan sosial kultural')",
            "sesuatu yang berkaitan dengan hasil kerja yang akan diterima oleh pelanggan ('Outcome')",
            "Sesungguhnya seorang pegawai yang loyal dapat dilihat dari seberapa ('Melakukan hal yang benar, dengan mengetahui bahwa orang lain tidak mengetahuinya')",
            "SEtiap instansi pemerintah wajib menyusun kebutuhan jumlah dan jenis jabatan PNS ('Anaklisis jabatan dan ananlisis beban kerja')",
            "Setiap instansi pemerintah wajib menyusun kebutuhan jumlah dan jenis jabatan PNS ('Dimensi kualitas pelayanan, dimensi modalitas, dan dimensi tindakan integritas')",
            "Setiap PNS MEMILIKI hak dan kesempatan untuk mengembangkan kompetensi ('Pengembangan kompetensi dilakukan atas permintaan individual pegawai')",
            "Sikap sopan yang harus diperlihatkan kepada pihak lain dalam suatu komunikasi ('Politeness')",
            "SISTEM PEMILIHAN PEJABAT berdasarkan afiliasi politik ('Spoil system')",
            "Situasi yang dapat menimbulkan konflik kepentingan seorang PNS  ('Memiliki saham disuatu perusahaan yang sedang mengikuti proses pengadaan barang dan jasa')",
            "Situasi yang dapat menimbulkan konflik kepentingan seorang PNS ('Aaa melakukan kerjasama dengan lembaga lain melalui kesepakatan resmi ( MOU ) ATAS nama instansi')",
            "Suatu perkumpulan pasti memiliki tujuan, demikian juga dengan Partai ('menetapkan garis perjuangan bersifat kooperatif')",
            "terdapat banyak sekali manfaat etiket bagi pegawai ASN ('Anglo saxon')",
            "Terdapat beberapa aspek yang dapat digunakan oleh organisasi ('Kemauan untuk Bekerja Sama')",
            "Tiga 3 (tiga) unsur penting dalam pelayanan publik adalah, kecuali ('Kepuasan penyelenggara pelayanan')",
            "Tindakan berikut yang dapat dilakukan ASN dalam menunjukkan sikap adil & netral ('Tidak diskriminatif dalam melayani')",
            "Tindakan yang KURANG TEPAT dalam perilaku ASN yang beretika ('Loyalitas hanya sebatas menyenangkan pimpinan, atau berusaha memenuhi kebutuhan pribadi pimpinanny')",
            "Tindakan yang tidak termasuk kategori whistle blower adalah kecuali ('Mengadukan pelaku pelanggaran etika kepada komite etika')",
            "Tolak ukur yang dipergunakan sebagai pedoman penyelenggaraan pelayanan ('Standar pelayanan')",
            "Tujuan utama dari akuntabilitas adalah. ('Untuk memperbaiki kinerja dalam memberikan pelayanan')",
            "Tujuan utama dari Nilai Dasar ASN ('Menjadi pedoman perilaku bagi para ASN dan menciptakan budaya kerja yang mendukung tercapainya kinerja terbaik')",
            "Tujuan utama pelayanan berbasis nilai ('Meningkatkan citra dan kesejahteraan pelanggan')",
            "TUJUAN Whole of govermen ( WGA ) SEBAGAI salah satu bentuk WOG ('Mendorong tranparansi dan akuntabilitas')",
            "tuntutan gencar yang dilakukan masyarakat kepada pejabat publik untuk ('PNS')",
            "Undang undang yang mengatur tentang pelayanan publik ('UU No 25 Th 2009')",
            "Undang-Undang Nomor 25 Tentang Layanan Publik menyebutkan 12 ('Kompetitif')",
            "Undang-undang yang mengatur tentang pelayanan publik ('UU No. 25 Tahun 2009')",
            "untuk menampilkan kinerja aparatur yang memiliki komitmen kuat ('Revolui inovasi layanan')",
            "Untuk mewujudkan organisasi public yang Akuntabel harus mengandung ('Semua jawaban benar')",
            "Upaya untuk melakukan kerja terbaik sebagai bagian perilaku kompeten ASN ('Melakukan adaptasi terhadap orang lain dan melakukan karya terbaik')",
            "UUD 1945 MENGatur hubungan antara pemerintah pusat dengan mengacu ('Pasal 18A')",
            "Walaupun sejak awal berdirinya budi utomo tidak ('Mengusulkan pembentukan volksread(dewan rakyat) bagi pribumi')",
            "Yang bertanggung jawab dalam memberikan pelayanan adalah ('Masyarakat')",
            "Yang bukan merupakan kendala dalam mengembangkan karya kreatif ('Dorongan melalukan perubahan')",
            "Yang bukan merupakan strategi yang mesti dijalankan organisasi ('Penggelembungan birokrasi')",
            "Yang bukan merupakan unsur penting dalam pelayanan publik ('Tempat pelayanan')",
            "Yang bukan prinsip pelayanan publik yang baik ('Kompleks namun murah')",
            "yang dapat menentukan tingkat produktivitas suatu organisasi ('Portal masing-masing kementerian dan lembaga')",
            "Yang dimaksud dengan affordance dalam konteks digital ('Kemudahan pada perangkat dan akses internet')",
            "Yang dimaksud dengan berorientasi pelayanan ('Komitmen memberikan pelayanan prima demi kepuasan masyarakat')",
            "Yang dimaksud dengan modalitas etika ('Jembatan antara norma moral dan tindakan factual')",
            "Yang mana kah diantara panduan perilaku berikut yang merupakan kode etik ('Ramah, cekatan, solutif dan dapat diandalkan')",
            "Yang mana kah diantara panduan perilaku berikut yang merupakan kode etik ('Memahami dan memenuhi kebutuhan masyarakat')",
            "Yang mana kah diantara panduan perilaku berikut yang merupakan kode etik ('Melakukan perbaikan tiada henti')",
            "Yang termasuk ciri pelayanan publik adalah ('Resiko kegagalan penyelenggaraan kerugian perseorangan')",
            "Yang tidak bisa dikategorikan nilai nilai anti korupsi ('Jujur empati andil')",
            "Yang tidak termasuk dalam pelayanan publik ('Hiburan')",
            "Yang tidak termasuk nilai nilai dasar anti korupi ('Simpati')",
            "Yang tidak termasuk panduan perilaku loyal dalam Core Values ('Melindungi segenap tumpah darah Indonesia dengan integritas dan semangat juang yang tinggi')",
            "Yang tidak termasuk prinsip-prinsip pelayanan publik ('Mengutamakan kepentingan pribadi')"
        ];

        // Fungsi untuk menampilkan barang yang sesuai dengan nama depan
        function filterBarang() {
            const input = document.getElementById('namaDepan').value.toLowerCase();
            const barangList = document.getElementById('barangList');
        
            // Mengosongkan daftar barang yang ada
            barangList.innerHTML = '';
        
            // Menyaring barang berdasarkan input
            const filteredBarang = barang.filter(item => item.toLowerCase().startsWith(input));
        
            // Menampilkan barang yang sesuai
            if (filteredBarang.length > 0) {
                filteredBarang.forEach(item => {
                    const li = document.createElement('li');
                    li.textContent = item;
                    barangList.appendChild(li);
                });
            } else {
                // Menampilkan pesan jika tidak ada hasil
                const li = document.createElement('li');
                li.textContent = 'kata tidak ada dalam daftar';
                barangList.appendChild(li);
            }
        }